fierlingerwiki: https://fierlinger.wiki.tum.de/Administration+Page
baseurl: /HimbeereCouch
usertitle: himbeerecouch
highlighter: pygments
include: 
  - _modules
  - _sources
  - _static

subsystems:
  - url: /api/html
    title: API documentation
