#!/bin/sh

### BEGIN INIT INFO
# Provides:		rspby
# Required-Start:	$all	
# Required-Stop:	$remote_fs $sys_log	
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:    Raspberry Pi Daemon	
# Description:    	Daemon for CouchDB/Raspberry Pi
### END INIT INFO

BASEDIR=/var/rspby
SERVERFILE=$BASEDIR/server
THISCMD=$1
PIP=/usr/local/bin/pip

runcommand() {
   python -c "import himbeerecouch.prog as p; p.run_daemon(\"$THISCMD\", \"$SERVERFILE\", \"$BASEDIR\")" || exit $?
}


case "$1" in
    install)
      echo "Installing newest version of himbeerecouch"
      $PIP install --upgrade https://github.com/nEDM-TUM/HimbeereCouch/tarball/master#egg=himbeerecouch || exit $?
    ;;
    start|stop|restart|reload)
      runcommand
    ;;
    *)
      echo "Usage: start|stop|restart|reload|install" 
      exit 1
    ;;
esac


exit 0
